import { createContext, useContext, useState } from "react";

const translations = {
  en: {
    // Settings page
    settings: "Settings",
    settingsDesc: "Manage your account settings and set e-mail preferences.",
    account: "Account",
    security: "Security",
    appearance: "Appearance",
    language: "Language",
    privacyPolicy: "Privacy Policy",
    supportCenter: "Support Center",
    logout: "Logout",
    // Account tab
    publicProfile: "Public Profile",
    publicProfileDesc: "Update your personal information visible to others.",
    changePhoto: "Change Photo",
    photoHint: "JPG, GIF or PNG. Max size 2MB.",
    username: "Username",
    emailAddress: "Email Address",
    firstName: "First Name",
    lastName: "Last Name",
    phoneNumber: "Phone Number",
    universityID: "University ID",
    wilaya: "Wilaya",
    updateProfile: "Update Profile",
    // Company Profile Fields
    companyName: "Company Name",
    companyLocation: "Location",
    companyWebsite: "Website",
    companyField: "Industry / Field",
    companyDescription: "Description",
    // Security tab
    securitySettings: "Security Settings",
    securityDesc: "Secure your account with a strong password.",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    changePassword: "Change Password",
    // Appearance tab
    appearanceSettings: "Appearance Settings",
    appearanceDesc: "Customize how the platform looks for you.",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    // Language tab
    languageSettings: "Language Settings",
    languageDesc: "Choose your preferred language for the platform.",
    // Privacy tab
    privacyDesc: "How we handle your data and protect your privacy.",
    infoCollect: "1. Information We Collect",
    infoCollectDesc: "We collect personal information that you provide to us such as name, email address, and profile details when you register on our platform.",
    howWeUse: "2. How We Use Your Information",
    howWeUseDesc: "We use your information to provide and improve our services, communicate with you, and ensure a personalized experience for both students and companies.",
    dataSecurity: "3. Data Security",
    dataSecurityDesc: "We implement industry-standard security measures to protect your personal data from unauthorized access, alteration, or disclosure.",
    yourRights: "4. Your Rights",
    yourRightsDesc: "You have the right to access, update, or delete your personal information at any time through your account settings.",
    lastUpdated: "Last updated: May 2024",
    // Support tab
    supportDesc: "Need help? We're here for you.",
    contactSupport: "Contact Support",
    contactSupportDesc: "Talk to our team",
    helpDocs: "Help Documentation",
    helpDocsDesc: "Read our guides",
    // Dialog
    confirmLanguageChange: "Change Language",
    confirmLanguageMsg: "Are you sure you want to change the language to",
    yes: "Yes, change",
    cancel: "Cancel",
    // Messages
    profileUpdated: "Profile updated successfully!",
    profileError: "Failed to update profile. Please try again.",
    passwordChanged: "Password changed successfully!",
    passwordMismatch: "New passwords do not match.",
    passwordError: "Failed to change password.",
    // Navbar
    navHome: "Home",
    navInternships: "Internships",
    navCompanies: "Companies",
    navAbout: "About Us",
    navDashboard: "Dashboard",
    navProfile: "View Profile",
    navNotifications: "Notifications",
    navSettings: "Settings",
    navLogin: "Log In",
    navRegister: "Register",
    // Footer
    footerDesc: "Connecting students with top companies for smarter internships. We streamline the matching and validation process for everyone.",
    footerExplore: "Explore",
    footerBrowse: "Browse Internships",
    footerCompanies: "Companies",
    footerHowItWorks: "How it Works",
    footerJoinNow: "Join Now",
    footerResources: "Resources",
    footerGuidelines: "Student Guidelines",
    footerFAQs: "FAQs",
    footerSupport: "Support Center",
    footerPrivacy: "Privacy Policy",
    footerContact: "Contact Us",
    footerRights: "© 2026 Inter.Ship Platform. All rights reserved.",
    // Home page
    heroTag: "New: AI-Powered Matching Now Available",
    heroTitle1: "Connecting Talent with",
    heroTitle2: "Opportunity.",
    heroDesc: "Inter.Ship is the premier platform for students to find meaningful internships and companies to discover the next generation of industry leaders.",
    heroBrowse: "Browse Internships",
    heroHow: "How it Works",
    trustedBy: "Trusted by leading universities and companies",
    featuresTitle: "Everything You Need",
    featuresDesc: "A complete platform designed to simplify internship management for all stakeholders.",
    featStudentPortal: "Student Portal",
    featStudentPortalDesc: "Complete profile management, CV builder, and internship application tracking all in one place.",
    featCompanyDash: "Company Dashboard",
    featCompanyDashDesc: "Post internship offers, review applications, and manage your recruitment pipeline efficiently.",
    featSmartMatch: "Smart Matching",
    featSmartMatchDesc: "AI-powered algorithm that matches students with the most suitable internship opportunities.",
    featDocGen: "Document Generation",
    featDocGenDesc: "Automatically generate internship agreements, certificates, and official documents.",
    featAdvSearch: "Advanced Search",
    featAdvSearchDesc: "Filter and find opportunities by skills, location, duration, and industry sector.",
    featAdminAnalytics: "Admin Analytics",
    featAdminAnalyticsDesc: "Comprehensive dashboards for universities to track placements and generate reports.",
    howTitle: "How It Works",
    howDesc: "Get started in four simple steps and find your perfect internship match.",
    howStep1: "Create Your Profile",
    howStep1Desc: "Students and companies register and complete their profiles with relevant information and requirements.",
    howStep2: "Browse & Match",
    howStep2Desc: "Our AI analyzes profiles and suggests the best matches. Students can also search and apply directly.",
    howStep3: "Apply & Review",
    howStep3Desc: "Students submit applications, companies review candidates and schedule interviews through the platform.",
    howStep4: "Get Your Agreement",
    howStep4Desc: "Once matched, the system automatically generates the internship agreement for all parties to sign.",
    builtForAll: "Built For Everyone",
    builtForAllDesc: "Whether you are a student looking for opportunities or a company seeking talent, Inter.Ship has you covered.",
    forStudents: "For Students",
    forStudentsDesc: "Launch your career with the perfect internship opportunity",
    studentFeat1: "Build a professional profile and CV",
    studentFeat2: "Get matched with relevant opportunities",
    studentFeat3: "Track all your applications in one place",
    studentFeat4: "Receive notifications for new matches",
    studentFeat5: "Download your internship agreement",
    joinAsStudent: "Join as Student",
    alreadyLoggedIn: "Already Logged In",
    forCompanies: "For Companies",
    forCompaniesDesc: "Find talented interns who match your requirements",
    companyFeat1: "Post unlimited internship offers",
    companyFeat2: "Access a pool of qualified candidates",
    companyFeat3: "AI-powered candidate recommendations",
    companyFeat4: "Streamlined interview scheduling",
    companyFeat5: "Digital agreement management",
    partnerWithUs: "Partner With Us",
    ctaTitle: "Ready to Get Started?",
    ctaDesc: "Join thousands of students and companies already using Inter.Ship to streamline their internship process.",
    createAccount: "Create an Account",
    accountActive: "Account Active",
    contactUs: "Contact Us",
    // Companies
    discoverCompanies: "Discover Companies",
    discoverCompaniesDesc: "Find and connect with top organizations looking for talent.",
    searchCompanies: "Search companies or industries...",
    loadingCompanies: "Loading amazing companies...",
    noDescCompany: "No description available for this company.",
    openPosition: "Open Position",
    openPositions: "Open Positions",
    viewDetails: "View Details",
    noCompaniesFound: "No companies found",
    noCompaniesMatch: "We couldn't find any companies matching your search.",
    clearSearch: "Clear search",
    tryAgain: "Try again",
    // Internships
    exploreInternships: "Explore Internships",
    exploreInternshipsDesc: "Find the best internship opportunities tailored for you.",
    searchInternships: "Search by title, company, or keywords...",
    filters: "Filters:",
    bySkillAll: "By Skill (All)",
    skillsSelected: "Skills Selected",
    clearSkills: "Clear Skills",
    byTypeAll: "By Type (All)",
    byLocationAll: "By Location (All)",
    byWilayaAll: "By Wilaya (All)",
    resultsFound: "Results Found",
    filtered: "Filtered",
    pressEnterToSearch: "Press Enter to search...",
    typeAnything: "Type anything or select a filter to start searching...",
    youCanRefine: "You can still refine using filters.",
    trySearchingFor: 'Try searching for "Software", "Google", or filter by Tech!',
    noInternshipsCriteria: "No internships found matching your criteria",
    pressToClose: "Press ESC to close",
    searchResultsAdvanced: "Search results by advanced filtering",
    couldntFindInternships: "We couldn't find anything matching your current filters. Try adjusting them or clear your search.",
    // About Us
    ourStory: "Our Story",
    empoweringNext: "Empowering the next",
    professionals: "Professionals.",
    aboutDesc: "Inter.Ship is more than just a platform—it's a bridge between ambition and achievement, connecting Algeria's brightest students with the nation's leading enterprises.",
    activeInternships: "Active Internships",
    verifiedStudents: "Verified Students",
    partnerCompanies: "Partner Companies",
    matchRate: "Match Rate",
    ourMission: "Our Mission",
    missionDesc: "Inter.Ship was founded in 2025 with a singular focus: to modernize how students start their professional journey in Algeria. We provide a centralized, smart platform for students to discover high-value internships and for companies to find the next generation of leaders.",
    accessibility: "Accessibility",
    accessibilityDesc: "Connecting talent from all 58 provinces to top enterprises.",
    innovation: "Innovation",
    innovationDesc: "Using smart algorithms to ensure the perfect candidate-role match.",
    ourVision: "Our Vision",
    visionDesc: "\"To become the definitive career launchpad for the African Mediterranean region, ensuring every motivated student has a clear path to professional excellence through impactful real-world experience.\"",
    drivenByGrowth: "Driven by Growth",
    makersOf: "The Makers of Inter.Ship",
    makersDesc: "Our diverse team combines educational expertise with world-class engineering to build a platform that truly serves the future of Algerian talent.",
    joinOurMission: "Join Our Mission",
    readyToLaunch: "Ready to launch your career?",
    readyToLaunchDesc: "Join the fastest-growing professional community in Algeria and start your journey today.",
    getStartedNow: "Get Started Now",
    // About Us Team
    roleFounder: "President & Founder",
    bioFounder: "Specializing in student career development with 10+ years of educational technology experience.",
    tagFounder: "Founder",
    roleTech: "Tech Lead",
    bioTech: "Passionate about building scalable platforms that connect students with industry leaders.",
    tagTech: "Lead Architect",
    rolePartnerships: "Partnerships Manager",
    bioPartnerships: "Ensuring world-class connections between top companies and Algerian universities.",
    tagPartnerships: "Operations",
    // Contact Us
    getInTouch: "Get in Touch",
    getInTouchDesc: "We'd love to hear from you. Our team is always here to chat.",
    sendAMessage: "Send a Message",
    subject: "Subject",
    yourMessage: "Your Message",
    sendMessage: "Send Message",
    contactInfo: "Contact Information",
    ourOffice: "Our Office",
    emailUs: "Email Us",
    callUs: "Call Us",
    // Auth
    letsJoinUs: "Let's join with us",
    signInJoin: "You can sign in or join with us if you're new to InterShip.",
    email: "Email",
    password: "Password",
    enterEmail: "Enter your email",
    forgotPassword: "Forgot Password?",
    login: "Login",
    loggingIn: "Logging in...",
    noAccount: "Don't have an account?",
    signUp: "Sign up",
    createAccountDesc: "Enter your details below to create your InterShip account.",
    registerAs: "Register as",
    student: "Student",
    company: "Company",
    admin: "Administrator",
    totalInternships: "Total Internships",
    open: "Open",
    closed: "Closed",
    noInternshipsFound: "No internships posted yet.",
    selectYear: "Select Year",
    industry: "Industry",
    companyOverview: "Company Overview",
    companyOverviewDesc: "Corporate and professional details",
    website: "Website",
    creatingAccount: "Creating account...",
    alreadyHaveAccount: "Already have an account?",
    // FAQ
    faqTitle: "Frequently Asked Questions",
    faqDesc: "Find answers to the most common questions about finding internships and managing your 'Convention de Stage'.",
    stillHaveQuestions: "Still have questions?",
    stillHaveQuestionsDesc: "If you cannot find the answer to your question in our FAQ, you can always ask us directly.",
    thinking: "Thinking...",
    typeQuestion: "Type your question here...",
    send: "Send",
    faqQ1: "What is this platform about?",
    faqA1: "This is a centralized University-Enterprise matching platform designed to automate the internship process. It connects students looking for internships with companies searching for the right profiles, completely digitizing the workflow.",
    faqQ2: "How do I create a student account?",
    faqA2: "You can register securely on the platform. We strongly recommend using your official University Email. Once registered, you must fill out your Digital CV with your technical skills, GitHub/Portfolio links, and personal details.",
    faqQ3: "How do I apply for an internship?",
    faqA3: "After completing your Digital CV, use the search tool to find internships based on your Wilaya, preferred technologies, or internship type. Click 'Apply' to send your profile directly to the recruiter.",
    faqQ4: "What happens after a company accepts me?",
    faqA4: "When a company accepts your application, the University Administration (Internship Office) receives an automatic notification to validate your placement. You don't need to do any manual paperwork!",
    faqQ5: "How do I get my 'Convention de Stage' (Internship Agreement)?",
    faqA5: "Once the University Administration validates your placement, the system automatically generates your official 'Convention de Stage' in PDF format. It will be pre-filled with all necessary data from you, the company, and the university, ready to be downloaded.",
    faqQ6: "Can companies create multiple internship offers?",
    faqA6: "Yes, recruiters can create, modify, and delete as many internship offers as they need from their dedicated Company Space.",
    // Guidelines
    guidelinesTitle: "Student Guidelines",
    guidelinesDesc: "Follow these steps to complete your digital profile, match with the perfect company, and easily generate your official internship agreement.",
    guide1Title: "1. Create Your Digital CV",
    guide1Content: "Register securely (preferably using your University Email) and build your digital CV. Make sure to accurately select your technical skills (e.g., React, Java, Python) and include links to your GitHub or Portfolio. A complete profile is essential for recruiters to evaluate your application.",
    guide2Title: "2. Search & Find Your Match",
    guide2Content: "Use the advanced search tools to find internship offers that fit your profile. You can filter opportunities by Wilaya, technology stack, and internship type to easily connect with the right companies.",
    guide3Title: "3. Apply & Track Progress",
    guide3Content: "Send your profile directly to companies with a single click. The company recruiter will review your digital CV. You can track your application status to see if you are accepted or refused.",
    guide4Title: "4. Automated Convention de Stage",
    guide4Content: "Say goodbye to manual paperwork! Once a company accepts your application, the university administration is automatically notified. After they validate your placement, the system will automatically generate your official 'Convention de Stage' in PDF format, pre-filled with all your details.",
    // Profile
    loadingProfile: "Loading your profile...",
    unableToLoad: "Unable to load profile data.",
    returnHome: "Return Home",
    joined: "Joined",
    memberSince: "Member since 2025",
    contactInformation: "Contact Information",
    notProvided: "Not provided",
    verifiedStatus: "Verified Status",
    verifiedStatusDesc: "Your account is fully certified and prioritized for top-tier internship matches.",
    professionalOverview: "Professional Overview",
    professionalOverviewDesc: "Your academic and career positioning",
    institution: "Institution",
    notSpecified: "Not specified",
    majorField: "Major / Field",
    undeclared: "Undeclared",
    operationsRegion: "Operations Region",
    experienceLevel: "Experience Level",
    verifiedEnterprise: "Verified Enterprise",
    aspiringProfessional: "Aspiring Professional",
    aboutMe: "About Me",
    noBioProvided: "No biography provided. A dedicated member of the Inter.Ship community looking forward to new professional opportunities.",
    // CompaniesDetails
    loadingCompanyDetails: "Loading company details...",
    companyNotFound: "Company not found.",
    failedToLoadCompany: "Failed to load company details.",
    backToCompanies: "Back to Companies",
    following: "Following",
    followCompany: "Follow Company",
    aboutUs: "About Us",
    benefitsPerks: "Benefits & Perks",
    companySnapshot: "Company Snapshot",
    founded: "Founded",
    field: "Field",
    companySize: "Company Size",
    headquarters: "Headquarters",
    visitWebsite: "Visit Website",
    weAreHiring: "We are hiring!",
    joinOurTeam: "Join our team and help us build the future.",
    openRoles: "Open Roles",
    viewOpportunities: "View Opportunities",
    corporatePartner: "Corporate Partner",
    notAvailable: "N/A",
    // InternshipDetails
    gatheringInfo: "Gathering internship info...",
    couldNotFindInternship: "Could not find this internship opportunity.",
    goBack: "Go Back",
    positions: "Positions",
    opportunityOverview: "Opportunity Overview",
    requiredSkills: "Required Skills",
    keyDetails: "Key Details",
    startsOn: "Starts on",
    endsOn: "Ends on",
    timeLeft: "Time Left",
    started: "Started",
    daysLeft: "days left",
    dayLeft: "day left",
    hoursLeft: "hours left",
    duration: "Duration",
    flexible: "Flexible",
    spotsFilled: "Spots Filled",
    workMode: "Work Mode",
    applicationRejected: "Application Rejected",
    applicationAccepted: "Application Accepted",
    applicationReceived: "Application Received",
    cancelApplication: "Cancel Application",
    wait: "Wait...",
    cannotApplyAgain: "You cannot apply again for this specific internship.",
    applyNow: "Apply Now",
    cvRequired: "CV Required",
    uploadCvUnlock: "Please upload your CV in your dashboard to unlock applications.",
    goToCvManager: "Go to CV Manager",
    sending: "Sending...",
    // Forgot Password
    forgotPasswordTitle: "Forgot Password?",
    verifyCode: "Verify Code",
    newPasswordTitle: "New Password",
    forgotSubtitle1: "No worries! Enter your email and we'll send you a reset code.",
    forgotSubtitle2: "We sent a 6-digit code to",
    forgotSubtitle3: "Create a strong new password for your account.",
    enterEmailError: "Please enter your email address.",
    validEmailError: "Please enter a valid email.",
    noAccountFound: "No account found with this email.",
    somethingWentWrong: "Something went wrong.",
    enter6Digit: "Please enter the 6-digit code.",
    invalidCode: "Connection error or invalid code.",
    enterNewPassword: "Please enter a new password.",
    passwordLength: "Must be at least 8 characters.",
    confirmYourPassword: "Please confirm your password.",
    passwordsDoNotMatch: "Passwords do not match.",
    failedToReset: "Failed to reset password.",
    failedToResend: "Failed to resend.",
    sendResetCode: "Send Reset Code",
    verifyCodeBtn: "Verify Code",
    didntReceive: "Didn't receive it?",
    resendIn: "Resend in",
    resendCode: "Resend Code",
    newPasswordLabel: "New Password",
    enterNewPasswordPlaceholder: "Enter new password",
    confirmPasswordLabel: "Confirm Password",
    confirmPasswordPlaceholder: "Confirm new password",
    weak: "Weak",
    fair: "Fair",
    strong: "Strong",
    veryStrong: "Very Strong",
    resetPasswordBtn: "Reset Password",
    passwordReset: "Password Reset!",
    passwordResetSuccess: "Your password has been reset successfully. You can now sign in with your new password.",
    backToSignIn: "Back to Sign In",
    // Sidebar
    sidebarDashboard: "Dashboard",
    sidebarOverview: "Overview",
    sidebarAnalytics: "Analytics",
    sidebarInternships: "Internships",
    sidebarBrowseAll: "Browse All",
    sidebarMyListings: "My Listings",
    sidebarNewPosting: "New Posting",
    sidebarApplications: "Applications",
    sidebarPlatform: "Platform",
    sidebarSettings: "Settings",
    sidebarHelpCenter: "Help Center",
    sidebarMyCV: "My CV",
    sidebarMyApplications: "My applications",
    sidebarUserManagement: "User Management",
    sidebarCompanies: "Companies",
    sidebarValidations: "Validations",
    sidebarMessages: "Messages",
    searchPlaceholder: "Search...",
    comingSoon: "Coming soon...",
    studentPlatform: "Student Platform",
    companyPlatform: "Company Platform",
    platformAdmin: "Platform Admin",
  },
  fr: {
    settings: "Paramètres",
    settingsDesc: "Gérez les paramètres de votre compte et vos préférences.",
    account: "Compte",
    security: "Sécurité",
    appearance: "Apparence",
    language: "Langue",
    privacyPolicy: "Politique de confidentialité",
    supportCenter: "Centre d'aide",
    logout: "Déconnexion",
    publicProfile: "Profil public",
    publicProfileDesc: "Mettez à jour vos informations personnelles visibles par les autres.",
    changePhoto: "Changer la photo",
    photoHint: "JPG, GIF ou PNG. Taille max 2 Mo.",
    username: "Nom d'utilisateur",
    emailAddress: "Adresse e-mail",
    firstName: "Prénom",
    lastName: "Nom de famille",
    phoneNumber: "Numéro de téléphone",
    universityID: "ID Universitaire",
    wilaya: "Wilaya",
    updateProfile: "Mettre à jour le profil",
    // Company Profile Fields
    companyName: "Nom de l'entreprise",
    companyLocation: "Emplacement",
    companyWebsite: "Site Web",
    companyField: "Secteur d'activité",
    companyDescription: "Description",
    // Settings
    securitySettings: "Paramètres de sécurité",
    securityDesc: "Sécurisez votre compte avec un mot de passe fort.",
    currentPassword: "Mot de passe actuel",
    newPassword: "Nouveau mot de passe",
    confirmPassword: "Confirmer le nouveau mot de passe",
    changePassword: "Changer le mot de passe",
    appearanceSettings: "Paramètres d'apparence",
    appearanceDesc: "Personnalisez l'apparence de la plateforme.",
    lightMode: "Mode clair",
    darkMode: "Mode sombre",
    languageSettings: "Paramètres de langue",
    languageDesc: "Choisissez votre langue préférée pour la plateforme.",
    privacyDesc: "Comment nous traitons vos données et protégeons votre vie privée.",
    infoCollect: "1. Informations que nous collectons",
    infoCollectDesc: "Nous collectons les informations personnelles que vous nous fournissez telles que le nom, l'adresse e-mail et les détails du profil lors de votre inscription sur notre plateforme.",
    howWeUse: "2. Comment nous utilisons vos informations",
    howWeUseDesc: "Nous utilisons vos informations pour fournir et améliorer nos services, communiquer avec vous et assurer une expérience personnalisée pour les étudiants et les entreprises.",
    dataSecurity: "3. Sécurité des données",
    dataSecurityDesc: "Nous mettons en œuvre des mesures de sécurité conformes aux normes de l'industrie pour protéger vos données personnelles contre tout accès, modification ou divulgation non autorisés.",
    yourRights: "4. Vos droits",
    yourRightsDesc: "Vous avez le droit d'accéder, de mettre à jour ou de supprimer vos informations personnelles à tout moment via les paramètres de votre compte.",
    lastUpdated: "Dernière mise à jour : Mai 2024",
    supportDesc: "Besoin d'aide ? Nous sommes là pour vous.",
    contactSupport: "Contacter le support",
    contactSupportDesc: "Parlez à notre équipe",
    helpDocs: "Documentation d'aide",
    helpDocsDesc: "Lisez nos guides",
    confirmLanguageChange: "Changer la langue",
    confirmLanguageMsg: "Êtes-vous sûr de vouloir changer la langue en",
    yes: "Oui, changer",
    cancel: "Annuler",
    profileUpdated: "Profil mis à jour avec succès !",
    profileError: "Échec de la mise à jour du profil. Veuillez réessayer.",
    passwordChanged: "Mot de passe changé avec succès !",
    passwordMismatch: "Les nouveaux mots de passe ne correspondent pas.",
    passwordError: "Échec du changement de mot de passe.",
    navHome: "Accueil",
    navInternships: "Stages",
    navCompanies: "Entreprises",
    navAbout: "À propos",
    navDashboard: "Tableau de bord",
    navProfile: "Voir le profil",
    navNotifications: "Notifications",
    navSettings: "Paramètres",
    navLogin: "Connexion",
    navRegister: "S'inscrire",
    footerDesc: "Connecter les étudiants aux meilleures entreprises pour des stages plus intelligents. Nous simplifions le processus de mise en relation et de validation pour tous.",
    footerExplore: "Explorer",
    footerBrowse: "Parcourir les stages",
    footerCompanies: "Entreprises",
    footerHowItWorks: "Comment ça marche",
    footerJoinNow: "Rejoindre",
    footerResources: "Ressources",
    footerGuidelines: "Guide étudiant",
    footerFAQs: "FAQ",
    footerSupport: "Centre d'aide",
    footerPrivacy: "Politique de confidentialité",
    footerContact: "Nous contacter",
    footerRights: "© 2026 Inter.Ship Platform. Tous droits réservés.",
    heroTag: "Nouveau : Correspondance IA maintenant disponible",
    heroTitle1: "Connecter le talent avec",
    heroTitle2: "l'Opportunité.",
    heroDesc: "Inter.Ship est la plateforme de référence pour les étudiants à la recherche de stages et les entreprises à la découverte de la prochaine génération de leaders.",
    heroBrowse: "Parcourir les stages",
    heroHow: "Comment ça marche",
    trustedBy: "Approuvé par les universités et entreprises de premier plan",
    featuresTitle: "Tout ce dont vous avez besoin",
    featuresDesc: "Une plateforme complète conçue pour simplifier la gestion des stages pour tous.",
    featStudentPortal: "Portail étudiant",
    featStudentPortalDesc: "Gestion de profil, création de CV et suivi des candidatures en un seul endroit.",
    featCompanyDash: "Tableau de bord entreprise",
    featCompanyDashDesc: "Publiez des offres de stage, examinez les candidatures et gérez votre processus de recrutement.",
    featSmartMatch: "Correspondance intelligente",
    featSmartMatchDesc: "Algorithme IA qui associe les étudiants aux opportunités de stage les plus adaptées.",
    featDocGen: "Génération de documents",
    featDocGenDesc: "Générez automatiquement les conventions de stage, certificats et documents officiels.",
    featAdvSearch: "Recherche avancée",
    featAdvSearchDesc: "Filtrez et trouvez des opportunités par compétences, lieu, durée et secteur.",
    featAdminAnalytics: "Analytique admin",
    featAdminAnalyticsDesc: "Tableaux de bord complets pour les universités pour suivre les placements et générer des rapports.",
    howTitle: "Comment ça marche",
    howDesc: "Commencez en quatre étapes simples et trouvez votre stage idéal.",
    howStep1: "Créez votre profil",
    howStep1Desc: "Les étudiants et les entreprises s'inscrivent et complètent leurs profils avec les informations pertinentes.",
    howStep2: "Parcourir et matcher",
    howStep2Desc: "Notre IA analyse les profils et suggère les meilleures correspondances.",
    howStep3: "Postuler et examiner",
    howStep3Desc: "Les étudiants soumettent leurs candidatures, les entreprises examinent les candidats via la plateforme.",
    howStep4: "Obtenez votre convention",
    howStep4Desc: "Une fois jumelé, le système génère automatiquement la convention de stage.",
    builtForAll: "Conçu pour tous",
    builtForAllDesc: "Que vous soyez étudiant ou entreprise, Inter.Ship vous couvre.",
    forStudents: "Pour les étudiants",
    forStudentsDesc: "Lancez votre carrière avec le stage parfait",
    studentFeat1: "Créez un profil professionnel et un CV",
    studentFeat2: "Soyez mis en relation avec les opportunités pertinentes",
    studentFeat3: "Suivez toutes vos candidatures en un seul endroit",
    studentFeat4: "Recevez des notifications pour les nouvelles correspondances",
    studentFeat5: "Téléchargez votre convention de stage",
    joinAsStudent: "Rejoindre en tant qu'étudiant",
    alreadyLoggedIn: "Déjà connecté",
    forCompanies: "Pour les entreprises",
    forCompaniesDesc: "Trouvez des stagiaires talentueux correspondant à vos besoins",
    companyFeat1: "Publiez des offres de stage illimitées",
    companyFeat2: "Accédez à un vivier de candidats qualifiés",
    companyFeat3: "Recommandations de candidats par IA",
    companyFeat4: "Planification d'entretiens simplifiée",
    companyFeat5: "Gestion numérique des conventions",
    partnerWithUs: "Devenez partenaire",
    ctaTitle: "Prêt à commencer ?",
    ctaDesc: "Rejoignez des milliers d'étudiants et d'entreprises qui utilisent Inter.Ship.",
    createAccount: "Créer un compte",
    accountActive: "Compte actif",
    contactUs: "Nous contacter",
    // Companies
    discoverCompanies: "Découvrir les entreprises",
    discoverCompaniesDesc: "Trouvez et connectez-vous avec les meilleures organisations à la recherche de talents.",
    searchCompanies: "Rechercher des entreprises ou des secteurs...",
    loadingCompanies: "Chargement des entreprises incroyables...",
    noDescCompany: "Aucune description disponible pour cette entreprise.",
    openPosition: "Poste ouvert",
    openPositions: "Postes ouverts",
    viewDetails: "Voir les détails",
    noCompaniesFound: "Aucune entreprise trouvée",
    noCompaniesMatch: "Nous n'avons trouvé aucune entreprise correspondant à votre recherche.",
    clearSearch: "Effacer la recherche",
    tryAgain: "Réessayer",
    // Internships
    exploreInternships: "Explorer les stages",
    exploreInternshipsDesc: "Trouvez les meilleures opportunités de stage pour vous.",
    searchInternships: "Rechercher par titre, entreprise ou mots-clés...",
    filters: "Filtres :",
    bySkillAll: "Par compétence (Tout)",
    skillsSelected: "Compétences sélectionnées",
    clearSkills: "Effacer les compétences",
    byTypeAll: "Par type (Tout)",
    byLocationAll: "Par lieu (Tout)",
    byWilayaAll: "Par Wilaya (Tout)",
    resultsFound: "Résultats trouvés",
    filtered: "Filtré",
    pressEnterToSearch: "Appuyez sur Entrée pour rechercher...",
    typeAnything: "Tapez quelque chose ou sélectionnez un filtre pour commencer...",
    youCanRefine: "Vous pouvez toujours affiner en utilisant les filtres.",
    trySearchingFor: 'Essayez de rechercher "Software", "Google", ou filtrez par Tech!',
    noInternshipsCriteria: "Aucun stage trouvé correspondant à vos critères",
    pressToClose: "Appuyez sur ESC pour fermer",
    searchResultsAdvanced: "Résultats de la recherche par filtrage avancé",
    couldntFindInternships: "Nous n'avons rien trouvé correspondant à vos filtres actuels. Essayez de les ajuster ou d'effacer votre recherche.",
    // About Us
    ourStory: "Notre Histoire",
    empoweringNext: "Habiliter les prochains",
    professionals: "Professionnels.",
    aboutDesc: "Inter.Ship est plus qu'une simple plateforme : c'est un pont entre l'ambition et la réussite, reliant les étudiants les plus brillants d'Algérie aux principales entreprises du pays.",
    activeInternships: "Stages Actifs",
    verifiedStudents: "Étudiants Vérifiés",
    partnerCompanies: "Entreprises Partenaires",
    matchRate: "Taux de Correspondance",
    ourMission: "Notre Mission",
    missionDesc: "Inter.Ship a été fondée en 2025 avec un objectif unique : moderniser la façon dont les étudiants commencent leur parcours professionnel en Algérie.",
    accessibility: "Accessibilité",
    accessibilityDesc: "Relier les talents des 58 wilayas aux meilleures entreprises.",
    innovation: "Innovation",
    innovationDesc: "Utiliser des algorithmes intelligents pour assurer la correspondance parfaite.",
    ourVision: "Notre Vision",
    visionDesc: "\"Devenir le tremplin professionnel définitif pour la région méditerranéenne africaine, en veillant à ce que chaque étudiant motivé ait un chemin clair vers l'excellence.\"",
    drivenByGrowth: "Guidé par la Croissance",
    makersOf: "Les Créateurs d'Inter.Ship",
    makersDesc: "Notre équipe diversifiée combine l'expertise éducative avec l'ingénierie de classe mondiale.",
    joinOurMission: "Rejoindre Notre Mission",
    readyToLaunch: "Prêt à lancer votre carrière ?",
    readyToLaunchDesc: "Rejoignez la communauté professionnelle à la croissance la plus rapide en Algérie et commencez votre voyage aujourd'hui.",
    getStartedNow: "Commencer Maintenant",
    // About Us Team
    roleFounder: "Président et Fondateur",
    bioFounder: "Spécialisé dans le développement de carrière des étudiants avec plus de 10 ans d'expérience en technologie éducative.",
    tagFounder: "Fondateur",
    roleTech: "Lead Technique",
    bioTech: "Passionné par la construction de plateformes évolutives qui connectent les étudiants aux leaders de l'industrie.",
    tagTech: "Architecte Principal",
    rolePartnerships: "Responsable des Partenariats",
    bioPartnerships: "Assure des connexions de classe mondiale entre les meilleures entreprises et les universités algériennes.",
    tagPartnerships: "Opérations",
    // Contact Us
    getInTouch: "Entrer en Contact",
    getInTouchDesc: "Nous aimerions avoir de vos nouvelles. Notre équipe est toujours là pour discuter.",
    sendAMessage: "Envoyer un Message",
    subject: "Sujet",
    yourMessage: "Votre Message",
    sendMessage: "Envoyer le Message",
    contactInfo: "Informations de Contact",
    ourOffice: "Notre Bureau",
    emailUs: "Envoyez-nous un Email",
    callUs: "Appelez-nous",
    // Auth
    letsJoinUs: "Rejoignez-nous",
    signInJoin: "Vous pouvez vous connecter ou nous rejoindre si vous êtes nouveau sur InterShip.",
    email: "E-mail",
    password: "Mot de passe",
    enterEmail: "Entrez votre e-mail",
    forgotPassword: "Mot de passe oublié ?",
    login: "Se connecter",
    loggingIn: "Connexion...",
    noAccount: "Vous n'avez pas de compte ?",
    signUp: "S'inscrire",
    createAccountDesc: "Entrez vos coordonnées ci-dessous pour créer votre compte InterShip.",
    registerAs: "S'inscrire en tant que",
    student: "Étudiant",
    company: "Entreprise",
    admin: "Administrateur",
    totalInternships: "Total des Stages",
    open: "Ouvert",
    closed: "Fermé",
    noInternshipsFound: "Aucun stage publié pour le moment.",
    selectYear: "Choisir l'année",
    industry: "Secteur",
    companyOverview: "Aperçu de l'entreprise",
    companyOverviewDesc: "Détails corporatifs et professionnels",
    website: "Site Web",
    creatingAccount: "Création du compte...",
    alreadyHaveAccount: "Vous avez déjà un compte ?",
    // FAQ
    faqTitle: "Foire Aux Questions",
    faqDesc: "Trouvez des réponses aux questions les plus courantes sur la recherche de stages et la gestion de votre 'Convention de Stage'.",
    stillHaveQuestions: "Vous avez encore des questions ?",
    stillHaveQuestionsDesc: "Si vous ne trouvez pas la réponse à votre question dans notre FAQ, vous pouvez toujours nous la poser directement.",
    thinking: "Réflexion...",
    typeQuestion: "Tapez votre question ici...",
    send: "Envoyer",
    faqQ1: "En quoi consiste cette plateforme ?",
    faqA1: "Il s'agit d'une plateforme centralisée de mise en relation Université-Entreprise conçue pour automatiser le processus de stage. Elle connecte les étudiants à la recherche de stages avec les entreprises cherchant les bons profils, numérisant complètement le flux de travail.",
    faqQ2: "Comment créer un compte étudiant ?",
    faqA2: "Vous pouvez vous inscrire en toute sécurité sur la plateforme. Nous vous recommandons vivement d'utiliser votre email universitaire officiel. Une fois inscrit, vous devez remplir votre CV numérique avec vos compétences techniques, liens GitHub/Portfolio et détails personnels.",
    faqQ3: "Comment postuler à un stage ?",
    faqA3: "Après avoir complété votre CV numérique, utilisez l'outil de recherche pour trouver des stages en fonction de votre wilaya, de vos technologies préférées ou du type de stage. Cliquez sur 'Postuler' pour envoyer votre profil directement au recruteur.",
    faqQ4: "Que se passe-t-il après qu'une entreprise m'a accepté ?",
    faqA4: "Lorsqu'une entreprise accepte votre candidature, l'administration universitaire (Bureau des stages) reçoit une notification automatique pour valider votre placement. Vous n'avez aucune formalité administrative manuelle à faire !",
    faqQ5: "Comment obtenir ma 'Convention de Stage' ?",
    faqA5: "Une fois que l'administration universitaire a validé votre placement, le système génère automatiquement votre 'Convention de Stage' officielle au format PDF. Elle sera pré-remplie avec toutes les données nécessaires vous concernant, l'entreprise et l'université, prête à être téléchargée.",
    faqQ6: "Les entreprises peuvent-elles créer plusieurs offres de stage ?",
    faqA6: "Oui, les recruteurs peuvent créer, modifier et supprimer autant d'offres de stage qu'ils en ont besoin depuis leur Espace Entreprise dédié.",
    // Guidelines
    guidelinesTitle: "Directives pour les Étudiants",
    guidelinesDesc: "Suivez ces étapes pour compléter votre profil numérique, trouver l'entreprise idéale et générer facilement votre convention de stage officielle.",
    guide1Title: "1. Créez Votre CV Numérique",
    guide1Content: "Inscrivez-vous en toute sécurité (de préférence avec votre e-mail universitaire) et créez votre CV numérique. Assurez-vous de sélectionner précisément vos compétences techniques et d'inclure des liens vers votre GitHub ou Portfolio.",
    guide2Title: "2. Recherchez & Trouvez Votre Correspondance",
    guide2Content: "Utilisez les outils de recherche avancés pour trouver des offres de stage qui correspondent à votre profil. Vous pouvez filtrer les opportunités par Wilaya, technologies et type de stage.",
    guide3Title: "3. Postulez & Suivez Vos Progrès",
    guide3Content: "Envoyez votre profil directement aux entreprises en un seul clic. Le recruteur examinera votre CV numérique. Vous pouvez suivre l'état de votre candidature.",
    guide4Title: "4. Convention de Stage Automatisée",
    guide4Content: "Dites adieu à la paperasse manuelle ! Une fois qu'une entreprise accepte votre candidature, l'administration universitaire est automatiquement informée et le système générera votre 'Convention de Stage' officielle en format PDF.",
    // Profile
    loadingProfile: "Chargement de votre profil...",
    unableToLoad: "Impossible de charger les données du profil.",
    returnHome: "Retour à l'accueil",
    joined: "Inscrit en",
    memberSince: "Membre depuis 2025",
    contactInformation: "Coordonnées",
    notProvided: "Non fourni",
    verifiedStatus: "Statut Vérifié",
    verifiedStatusDesc: "Votre compte est entièrement certifié et prioritaire pour les meilleures offres de stage.",
    professionalOverview: "Aperçu Professionnel",
    professionalOverviewDesc: "Votre positionnement académique et professionnel",
    institution: "Établissement",
    notSpecified: "Non spécifié",
    majorField: "Domaine / Spécialité",
    undeclared: "Non déclaré",
    operationsRegion: "Région d'Opérations",
    experienceLevel: "Niveau d'Expérience",
    verifiedEnterprise: "Entreprise Vérifiée",
    aspiringProfessional: "Professionnel en Devenir",
    aboutMe: "À propos de moi",
    noBioProvided: "Aucune biographie fournie. Un membre dévoué de la communauté Inter.Ship dans l'attente de nouvelles opportunités professionnelles.",
    // CompaniesDetails
    loadingCompanyDetails: "Chargement des détails de l'entreprise...",
    companyNotFound: "Entreprise non trouvée.",
    failedToLoadCompany: "Échec du chargement des détails de l'entreprise.",
    backToCompanies: "Retour aux Entreprises",
    following: "Abonné",
    followCompany: "Suivre l'entreprise",
    aboutUs: "À propos de nous",
    benefitsPerks: "Avantages et Bénéfices",
    companySnapshot: "Aperçu de l'entreprise",
    founded: "Fondée en",
    field: "Domaine",
    companySize: "Taille de l'entreprise",
    headquarters: "Siège social",
    visitWebsite: "Visiter le site Web",
    weAreHiring: "Nous recrutons !",
    joinOurTeam: "Rejoignez notre équipe et aidez-nous à construire l'avenir.",
    openRoles: "Postes ouverts",
    viewOpportunities: "Voir les opportunités",
    corporatePartner: "Partenaire Corporate",
    notAvailable: "N/D",
    // InternshipDetails
    gatheringInfo: "Collecte des informations sur le stage...",
    couldNotFindInternship: "Impossible de trouver cette offre de stage.",
    goBack: "Retour",
    positions: "Postes",
    opportunityOverview: "Aperçu de l'Opportunité",
    requiredSkills: "Compétences Requises",
    keyDetails: "Détails Clés",
    startsOn: "Commence le",
    endsOn: "Se termine le",
    timeLeft: "Temps Restant",
    started: "Commencé",
    daysLeft: "jours restants",
    dayLeft: "jour restant",
    hoursLeft: "heures restantes",
    duration: "Durée",
    flexible: "Flexible",
    spotsFilled: "Places Remplies",
    workMode: "Mode de Travail",
    applicationRejected: "Candidature Rejetée",
    applicationAccepted: "Candidature Acceptée",
    applicationReceived: "Candidature Reçue",
    cancelApplication: "Annuler la Candidature",
    wait: "Patientez...",
    cannotApplyAgain: "Vous ne pouvez pas postuler de nouveau à ce stage spécifique.",
    applyNow: "Postuler Maintenant",
    cvRequired: "CV Requis",
    uploadCvUnlock: "Veuillez télécharger votre CV dans votre tableau de bord pour débloquer les candidatures.",
    goToCvManager: "Aller au Gestionnaire de CV",
    sending: "Envoi...",
    // Forgot Password
    forgotPasswordTitle: "Mot de passe oublié ?",
    verifyCode: "Vérifier le code",
    newPasswordTitle: "Nouveau mot de passe",
    forgotSubtitle1: "Pas de soucis ! Entrez votre e-mail et nous vous enverrons un code de réinitialisation.",
    forgotSubtitle2: "Nous avons envoyé un code à 6 chiffres à",
    forgotSubtitle3: "Créez un nouveau mot de passe fort pour votre compte.",
    enterEmailError: "Veuillez entrer votre adresse e-mail.",
    validEmailError: "Veuillez entrer une adresse e-mail valide.",
    noAccountFound: "Aucun compte trouvé avec cet e-mail.",
    somethingWentWrong: "Une erreur s'est produite.",
    enter6Digit: "Veuillez entrer le code à 6 chiffres.",
    invalidCode: "Erreur de connexion ou code invalide.",
    enterNewPassword: "Veuillez entrer un nouveau mot de passe.",
    passwordLength: "Doit comporter au moins 8 caractères.",
    confirmYourPassword: "Veuillez confirmer votre mot de passe.",
    passwordsDoNotMatch: "Les mots de passe ne correspondent pas.",
    failedToReset: "Échec de la réinitialisation du mot de passe.",
    failedToResend: "Échec du renvoi.",
    sendResetCode: "Envoyer le code de réinitialisation",
    verifyCodeBtn: "Vérifier le code",
    didntReceive: "Vous ne l'avez pas reçu ?",
    resendIn: "Renvoyer dans",
    resendCode: "Renvoyer le code",
    newPasswordLabel: "Nouveau mot de passe",
    enterNewPasswordPlaceholder: "Entrer le nouveau mot de passe",
    confirmPasswordLabel: "Confirmer le mot de passe",
    confirmPasswordPlaceholder: "Confirmer le nouveau mot de passe",
    weak: "Faible",
    fair: "Moyen",
    strong: "Fort",
    veryStrong: "Très Fort",
    resetPasswordBtn: "Réinitialiser le mot de passe",
    passwordReset: "Mot de passe réinitialisé !",
    passwordResetSuccess: "Votre mot de passe a été réinitialisé avec succès. Vous pouvez maintenant vous connecter avec votre nouveau mot de passe.",
    backToSignIn: "Retour à la connexion",
    // Sidebar
    sidebarDashboard: "Tableau de bord",
    sidebarOverview: "Aperçu",
    sidebarAnalytics: "Analytique",
    sidebarInternships: "Stages",
    sidebarBrowseAll: "Parcourir tout",
    sidebarMyListings: "Mes annonces",
    sidebarNewPosting: "Nouvelle annonce",
    sidebarApplications: "Candidatures",
    sidebarPlatform: "Plateforme",
    sidebarSettings: "Paramètres",
    sidebarHelpCenter: "Centre d'aide",
    sidebarMyCV: "Mon CV",
    sidebarMyApplications: "Mes candidatures",
    sidebarUserManagement: "Gestion des utilisateurs",
    sidebarCompanies: "Entreprises",
    sidebarValidations: "Validations",
    sidebarMessages: "Messages",
    searchPlaceholder: "Rechercher...",
    comingSoon: "À venir...",
    studentPlatform: "Plateforme Étudiant",
    companyPlatform: "Plateforme Entreprise",
    platformAdmin: "Admin Plateforme",
  },
  ar: {
    settings: "الإعدادات",
    settingsDesc: "إدارة إعدادات حسابك وتفضيلاتك.",
    account: "الحساب",
    security: "الأمان",
    appearance: "المظهر",
    language: "اللغة",
    privacyPolicy: "سياسة الخصوصية",
    supportCenter: "مركز الدعم",
    logout: "تسجيل الخروج",
    publicProfile: "الملف الشخصي العام",
    publicProfileDesc: "قم بتحديث معلوماتك الشخصية المرئية للآخرين.",
    changePhoto: "تغيير الصورة",
    photoHint: "JPG أو GIF أو PNG. الحجم الأقصى 2 ميجابايت.",
    username: "اسم المستخدم",
    emailAddress: "البريد الإلكتروني",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    phoneNumber: "رقم الهاتف",
    universityID: "رقم الطالب",
    wilaya: "الولاية",
    updateProfile: "تحديث الملف الشخصي",
    // Company Profile Fields
    companyName: "اسم الشركة",
    companyLocation: "الموقع",
    companyWebsite: "الموقع الإلكتروني",
    companyField: "مجال العمل",
    companyDescription: "الوصف",
    // Settings
    securitySettings: "إعدادات الأمان",
    securityDesc: "قم بتأمين حسابك بكلمة مرور قوية.",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور الجديدة",
    changePassword: "تغيير كلمة المرور",
    appearanceSettings: "إعدادات المظهر",
    appearanceDesc: "خصص مظهر المنصة حسب رغبتك.",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    languageSettings: "إعدادات اللغة",
    languageDesc: "اختر لغتك المفضلة للمنصة.",
    privacyDesc: "كيف نتعامل مع بياناتك ونحمي خصوصيتك.",
    infoCollect: "١. المعلومات التي نجمعها",
    infoCollectDesc: "نجمع المعلومات الشخصية التي تقدمها لنا مثل الاسم وعنوان البريد الإلكتروني وتفاصيل الملف الشخصي عند التسجيل في منصتنا.",
    howWeUse: "٢. كيف نستخدم معلوماتك",
    howWeUseDesc: "نستخدم معلوماتك لتقديم خدماتنا وتحسينها والتواصل معك وضمان تجربة شخصية للطلاب والشركات.",
    dataSecurity: "٣. أمان البيانات",
    dataSecurityDesc: "ننفذ إجراءات أمنية وفقًا لمعايير الصناعة لحماية بياناتك الشخصية من الوصول غير المصرح به أو التعديل أو الكشف.",
    yourRights: "٤. حقوقك",
    yourRightsDesc: "لديك الحق في الوصول إلى معلوماتك الشخصية أو تحديثها أو حذفها في أي وقت من خلال إعدادات حسابك.",
    lastUpdated: "آخر تحديث: مايو 2024",
    supportDesc: "تحتاج مساعدة؟ نحن هنا من أجلك.",
    contactSupport: "اتصل بالدعم",
    contactSupportDesc: "تحدث مع فريقنا",
    helpDocs: "وثائق المساعدة",
    helpDocsDesc: "اقرأ أدلتنا",
    confirmLanguageChange: "تغيير اللغة",
    confirmLanguageMsg: "هل أنت متأكد أنك تريد تغيير اللغة إلى",
    yes: "نعم، غيّر",
    cancel: "إلغاء",
    profileUpdated: "تم تحديث الملف الشخصي بنجاح!",
    profileError: "فشل تحديث الملف الشخصي. يرجى المحاولة مرة أخرى.",
    passwordChanged: "تم تغيير كلمة المرور بنجاح!",
    passwordMismatch: "كلمات المرور الجديدة غير متطابقة.",
    passwordError: "فشل تغيير كلمة المرور.",
    navHome: "الرئيسية",
    navInternships: "التدريبات",
    navCompanies: "الشركات",
    navAbout: "من نحن",
    navDashboard: "لوحة التحكم",
    navProfile: "عرض الملف الشخصي",
    navNotifications: "الإشعارات",
    navSettings: "الإعدادات",
    navLogin: "تسجيل الدخول",
    navRegister: "إنشاء حساب",
    footerDesc: "ربط الطلاب بأفضل الشركات لتدريبات أذكى. نبسّط عملية المطابقة والتحقق للجميع.",
    footerExplore: "استكشاف",
    footerBrowse: "تصفح التدريبات",
    footerCompanies: "الشركات",
    footerHowItWorks: "كيف يعمل",
    footerJoinNow: "انضم الآن",
    footerResources: "الموارد",
    footerGuidelines: "دليل الطالب",
    footerFAQs: "الأسئلة الشائعة",
    footerSupport: "مركز الدعم",
    footerPrivacy: "سياسة الخصوصية",
    footerContact: "اتصل بنا",
    footerRights: "© 2026 Inter.Ship Platform. جميع الحقوق محفوظة.",
    heroTag: "جديد: المطابقة بالذكاء الاصطناعي متاحة الآن",
    heroTitle1: "ربط المواهب مع",
    heroTitle2: "الفرصة.",
    heroDesc: "Inter.Ship هي المنصة الرائدة للطلاب للعثور على تدريبات وللشركات لاكتشاف الجيل القادم من القادة.",
    heroBrowse: "تصفح التدريبات",
    heroHow: "كيف يعمل",
    trustedBy: "موثوق من قبل الجامعات والشركات الرائدة",
    featuresTitle: "كل ما تحتاجه",
    featuresDesc: "منصة شاملة مصممة لتبسيط إدارة التدريبات لجميع الأطراف.",
    featStudentPortal: "بوابة الطالب",
    featStudentPortalDesc: "إدارة الملف الشخصي وإنشاء السيرة الذاتية وتتبع الطلبات في مكان واحد.",
    featCompanyDash: "لوحة تحكم الشركة",
    featCompanyDashDesc: "انشر عروض التدريب وراجع الطلبات وأدر عملية التوظيف بكفاءة.",
    featSmartMatch: "المطابقة الذكية",
    featSmartMatchDesc: "خوارزمية ذكاء اصطناعي تربط الطلاب بأنسب فرص التدريب.",
    featDocGen: "إنشاء المستندات",
    featDocGenDesc: "إنشاء اتفاقيات التدريب والشهادات والوثائق الرسمية تلقائياً.",
    featAdvSearch: "البحث المتقدم",
    featAdvSearchDesc: "فلتر وابحث عن الفرص حسب المهارات والموقع والمدة والقطاع.",
    featAdminAnalytics: "تحليلات الإدارة",
    featAdminAnalyticsDesc: "لوحات تحكم شاملة للجامعات لتتبع التوظيف وإنشاء التقارير.",
    howTitle: "كيف يعمل",
    howDesc: "ابدأ في أربع خطوات بسيطة وجد تدريبك المثالي.",
    howStep1: "أنشئ ملفك الشخصي",
    howStep1Desc: "يسجل الطلاب والشركات ويكملون ملفاتهم الشخصية بالمعلومات المطلوبة.",
    howStep2: "تصفح وتطابق",
    howStep2Desc: "يحلل الذكاء الاصطناعي الملفات ويقترح أفضل التطابقات.",
    howStep3: "تقدم وراجع",
    howStep3Desc: "يقدم الطلاب طلباتهم وتراجع الشركات المرشحين عبر المنصة.",
    howStep4: "احصل على اتفاقيتك",
    howStep4Desc: "بمجرد التطابق، ينشئ النظام اتفاقية التدريب تلقائياً.",
    builtForAll: "مصمم للجميع",
    builtForAllDesc: "سواء كنت طالباً يبحث عن فرص أو شركة تبحث عن مواهب، Inter.Ship يغطيك.",
    forStudents: "للطلاب",
    forStudentsDesc: "ابدأ مسيرتك المهنية بفرصة التدريب المثالية",
    studentFeat1: "أنشئ ملفاً شخصياً وسيرة ذاتية احترافية",
    studentFeat2: "تطابق مع الفرص المناسبة",
    studentFeat3: "تتبع جميع طلباتك في مكان واحد",
    studentFeat4: "استقبل إشعارات للتطابقات الجديدة",
    studentFeat5: "حمّل اتفاقية التدريب الخاصة بك",
    joinAsStudent: "انضم كطالب",
    alreadyLoggedIn: "تم تسجيل الدخول",
    forCompanies: "للشركات",
    forCompaniesDesc: "اعثر على متدربين موهوبين يتوافقون مع متطلباتك",
    companyFeat1: "انشر عروض تدريب غير محدودة",
    companyFeat2: "الوصول إلى مجموعة من المرشحين المؤهلين",
    companyFeat3: "توصيات المرشحين بالذكاء الاصطناعي",
    companyFeat4: "جدولة مقابلات مبسطة",
    companyFeat5: "إدارة الاتفاقيات الرقمية",
    partnerWithUs: "كن شريكاً معنا",
    ctaTitle: "مستعد للبدء؟",
    ctaDesc: "انضم إلى آلاف الطلاب والشركات الذين يستخدمون Inter.Ship.",
    createAccount: "إنشاء حساب",
    accountActive: "الحساب نشط",
    contactUs: "اتصل بنا",
    // Companies
    discoverCompanies: "اكتشف الشركات",
    discoverCompaniesDesc: "ابحث وتواصل مع أفضل المنظمات التي تبحث عن المواهب.",
    searchCompanies: "البحث عن شركات أو قطاعات...",
    loadingCompanies: "جاري تحميل الشركات الرائعة...",
    noDescCompany: "لا يوجد وصف متاح لهذه الشركة.",
    openPosition: "منصب شاغر",
    openPositions: "مناصب شاغرة",
    viewDetails: "عرض التفاصيل",
    noCompaniesFound: "لم يتم العثور على شركات",
    noCompaniesMatch: "لم نتمكن من العثور على أي شركات تطابق بحثك.",
    clearSearch: "مسح البحث",
    tryAgain: "حاول مرة أخرى",
    // Internships
    exploreInternships: "استكشف التدريبات",
    exploreInternshipsDesc: "ابحث عن أفضل فرص التدريب المصممة لك.",
    searchInternships: "البحث عن طريق العنوان أو الشركة أو الكلمات الرئيسية...",
    filters: "عوامل التصفية:",
    bySkillAll: "حسب المهارة (الكل)",
    skillsSelected: "المهارات المحددة",
    clearSkills: "مسح المهارات",
    byTypeAll: "حسب النوع (الكل)",
    byLocationAll: "حسب الموقع (الكل)",
    byWilayaAll: "حسب الولاية (الكل)",
    resultsFound: "نتائج وجدت",
    filtered: "مصفى",
    pressEnterToSearch: "اضغط على Enter للبحث...",
    typeAnything: "اكتب أي شيء أو حدد عامل تصفية لبدء البحث...",
    youCanRefine: "لا يزال بإمكانك التحسين باستخدام عوامل التصفية.",
    trySearchingFor: 'حاول البحث عن "Software" ، "Google" ، أو التصفية بواسطة التكنولوجيا!',
    noInternshipsCriteria: "لم يتم العثور على تدريبات تطابق معاييرك",
    pressToClose: "اضغط على ESC للإغلاق",
    searchResultsAdvanced: "نتائج البحث بواسطة التصفية المتقدمة",
    couldntFindInternships: "لم نتمكن من العثور على أي شيء يطابق عوامل التصفية الحالية الخاصة بك. حاول ضبطها أو امسح بحثك.",
    // About Us
    ourStory: "قصتنا",
    empoweringNext: "تمكين القادمين",
    professionals: "المهنيين.",
    aboutDesc: "Inter.Ship هي أكثر من مجرد منصة - إنها جسر بين الطموح والإنجاز، تربط ألمع الطلاب في الجزائر بالشركات الرائدة في البلاد.",
    activeInternships: "التدريبات النشطة",
    verifiedStudents: "الطلاب المعتمدين",
    partnerCompanies: "الشركات الشريكة",
    matchRate: "معدل التطابق",
    ourMission: "مهمتنا",
    missionDesc: "تأسست Inter.Ship في عام 2025 بتركيز فريد: تحديث كيفية بدء الطلاب لرحلتهم المهنية في الجزائر.",
    accessibility: "سهولة الوصول",
    accessibilityDesc: "ربط المواهب من جميع الولايات الـ 58 بأفضل الشركات.",
    innovation: "الابتكار",
    innovationDesc: "استخدام خوارزميات ذكية لضمان التطابق المثالي.",
    ourVision: "رؤيتنا",
    visionDesc: "\"أن نصبح منصة الانطلاق المهنية النهائية لمنطقة البحر الأبيض المتوسط الأفريقية، مع ضمان مسار واضح للتميز لكل طالب متحمس.\"",
    drivenByGrowth: "مدفوعون بالنمو",
    makersOf: "صناع Inter.Ship",
    makersDesc: "يجمع فريقنا المتنوع بين الخبرة التعليمية والهندسة ذات المستوى العالمي.",
    joinOurMission: "انضم إلى مهمتنا",
    readyToLaunch: "مستعد لبدء مسيرتك المهنية؟",
    readyToLaunchDesc: "انضم إلى أسرع مجتمع مهني نموًا في الجزائر وابدأ رحلتك اليوم.",
    getStartedNow: "ابدأ الآن",
    // About Us Team
    roleFounder: "الرئيس والمؤسس",
    bioFounder: "متخصص في التطوير المهني للطلاب مع أكثر من 10 سنوات من الخبرة في تكنولوجيا التعليم.",
    tagFounder: "المؤسس",
    roleTech: "الرئيس التقني",
    bioTech: "شغوف ببناء منصات قابلة للتطوير تربط الطلاب بقادة الصناعة.",
    tagTech: "المهندس المعماري الرئيسي",
    rolePartnerships: "مدير الشراكات",
    bioPartnerships: "ضمان اتصالات عالمية المستوى بين كبرى الشركات والجامعات الجزائرية.",
    tagPartnerships: "العمليات",
    // Contact Us
    getInTouch: "ابق على تواصل",
    getInTouchDesc: "نود أن نسمع منك. فريقنا متواجد دائمًا للدردشة.",
    sendAMessage: "إرسال رسالة",
    subject: "الموضوع",
    yourMessage: "رسالتك",
    sendMessage: "إرسال الرسالة",
    contactInfo: "معلومات الاتصال",
    ourOffice: "مكتبنا",
    emailUs: "راسلنا",
    callUs: "اتصل بنا",
    // Auth
    letsJoinUs: "انضم إلينا",
    signInJoin: "يمكنك تسجيل الدخول أو الانضمام إلينا إذا كنت جديدًا في InterShip.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    enterEmail: "أدخل بريدك الإلكتروني",
    forgotPassword: "هل نسيت كلمة المرور؟",
    login: "تسجيل الدخول",
    loggingIn: "جاري تسجيل الدخول...",
    noAccount: "ليس لديك حساب؟",
    signUp: "اشتراك",
    createAccountDesc: "أدخل بياناتك أدناه لإنشاء حساب InterShip الخاص بك.",
    registerAs: "التسجيل كـ",
    student: "طالب",
    company: "شركة",
    admin: "مدير النظام",
    totalInternships: "إجمالي التربصات",
    open: "مفتوح",
    closed: "مغلق",
    noInternshipsFound: "لم يتم نشر أي تربصات بعد.",
    selectYear: "اختر السنة",
    industry: "المجال",
    companyOverview: "لمحة عن الشركة",
    companyOverviewDesc: "التفاصيل المهنية والشركاتية",
    website: "الموقع الإلكتروني",
    creatingAccount: "جاري إنشاء الحساب...",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    // FAQ
    faqTitle: "الأسئلة الشائعة",
    faqDesc: "ابحث عن إجابات للأسئلة الأكثر شيوعًا حول العثور على تدريبات وإدارة 'اتفاقية التدريب' الخاصة بك.",
    stillHaveQuestions: "لا تزال لديك أسئلة؟",
    stillHaveQuestionsDesc: "إذا لم تتمكن من العثور على إجابة لسؤالك في الأسئلة الشائعة لدينا ، يمكنك دائمًا سؤالنا مباشرة.",
    thinking: "جاري التفكير...",
    typeQuestion: "اكتب سؤالك هنا...",
    send: "إرسال",
    faqQ1: "ما هي هذه المنصة؟",
    faqA1: "هذه منصة مركزية للتوفيق بين الجامعة والشركة مصممة لأتمتة عملية التدريب. إنها تربط الطلاب الذين يبحثون عن تدريب بالشركات التي تبحث عن الملفات الشخصية المناسبة، مما يؤدي إلى رقمنة سير العمل بالكامل.",
    faqQ2: "كيف يمكنني إنشاء حساب طالب؟",
    faqA2: "يمكنك التسجيل بأمان على المنصة. نوصي بشدة باستخدام بريدك الإلكتروني الجامعي الرسمي. بمجرد التسجيل، يجب عليك ملء سيرتك الذاتية الرقمية بمهاراتك التقنية، وروابط GitHub/Portfolio، وتفاصيلك الشخصية.",
    faqQ3: "كيف يمكنني التقديم على تدريب؟",
    faqA3: "بعد إكمال سيرتك الذاتية الرقمية، استخدم أداة البحث للعثور على تدريبات بناءً على ولايتك أو التقنيات المفضلة أو نوع التدريب. انقر على 'تقديم' لإرسال ملفك الشخصي مباشرة إلى مسؤول التوظيف.",
    faqQ4: "ماذا يحدث بعد أن تقبلني شركة؟",
    faqA4: "عندما تقبل شركة طلبك، تتلقى إدارة الجامعة (مكتب التدريب) إشعارًا تلقائيًا للتحقق من وضعك. لا تحتاج إلى القيام بأي أعمال ورقية يدوية!",
    faqQ5: "كيف أحصل على 'اتفاقية التدريب' (Convention de Stage) الخاصة بي؟",
    faqA5: "بمجرد أن تتحقق إدارة الجامعة من وضعك، يقوم النظام تلقائيًا بإنشاء 'اتفاقية التدريب' الرسمية الخاصة بك بتنسيق PDF. سيتم تعبئتها مسبقًا بجميع البيانات اللازمة منك، ومن الشركة، ومن الجامعة، وتكون جاهزة للتنزيل.",
    faqQ6: "هل يمكن للشركات إنشاء عروض تدريب متعددة؟",
    faqA6: "نعم، يمكن لمسؤولي التوظيف إنشاء أو تعديل أو حذف أي عدد يحتاجونه من عروض التدريب من مساحة الشركة المخصصة لهم.",
    // Guidelines
    guidelinesTitle: "إرشادات الطلاب",
    guidelinesDesc: "اتبع هذه الخطوات لإكمال ملفك الشخصي الرقمي، والتطابق مع الشركة المثالية، وإنشاء اتفاقية التدريب الرسمية الخاصة بك بسهولة.",
    guide1Title: "1. قم بإنشاء سيرتك الذاتية الرقمية",
    guide1Content: "قم بالتسجيل بشكل آمن (يُفضل استخدام بريدك الجامعي) وقم ببناء سيرتك الذاتية الرقمية. تأكد من تحديد مهاراتك الفنية بدقة وتضمين روابط إلى GitHub أو محفظتك.",
    guide2Title: "2. ابحث واعثر على التطابق الخاص بك",
    guide2Content: "استخدم أدوات البحث المتقدمة للعثور على عروض التدريب التي تناسب ملفك الشخصي. يمكنك تصفية الفرص حسب الولاية ومجموعة التكنولوجيا ونوع التدريب.",
    guide3Title: "3. التقديم وتتبع التقدم",
    guide3Content: "أرسل ملفك الشخصي مباشرة إلى الشركات بنقرة واحدة. سيقوم مسؤول التوظيف في الشركة بمراجعة سيرتك الذاتية الرقمية. يمكنك تتبع حالة طلبك.",
    guide4Title: "4. اتفاقية تدريب مؤتمتة",
    guide4Content: "قل وداعًا للأعمال الورقية اليدوية! بمجرد قبول الشركة لطلبك ، يتم إخطار إدارة الجامعة تلقائيًا وسيقوم النظام تلقائيًا بإنشاء 'اتفاقية التدريب' الرسمية الخاصة بك بتنسيق PDF.",
    // Profile
    loadingProfile: "جاري تحميل ملفك الشخصي...",
    unableToLoad: "غير قادر على تحميل بيانات الملف الشخصي.",
    returnHome: "العودة للرئيسية",
    joined: "انضم",
    memberSince: "عضو منذ 2025",
    contactInformation: "معلومات الاتصال",
    notProvided: "غير متوفر",
    verifiedStatus: "حالة التحقق",
    verifiedStatusDesc: "حسابك معتمد بالكامل ويحظى بالأولوية لأفضل فرص التدريب.",
    professionalOverview: "نظرة عامة مهنية",
    professionalOverviewDesc: "موقفك الأكاديمي والمهني",
    institution: "المؤسسة",
    notSpecified: "غير محدد",
    majorField: "التخصص / المجال",
    undeclared: "غير معلن",
    operationsRegion: "منطقة العمليات",
    experienceLevel: "مستوى الخبرة",
    verifiedEnterprise: "مؤسسة معتمدة",
    aspiringProfessional: "محترف طموح",
    aboutMe: "نبذة عني",
    noBioProvided: "لم يتم تقديم سيرة ذاتية. عضو متفاني في مجتمع Inter.Ship يتطلع إلى فرص مهنية جديدة.",
    // CompaniesDetails
    loadingCompanyDetails: "جاري تحميل تفاصيل الشركة...",
    companyNotFound: "الشركة غير موجودة.",
    failedToLoadCompany: "فشل في تحميل تفاصيل الشركة.",
    backToCompanies: "العودة للشركات",
    following: "متابع",
    followCompany: "متابعة الشركة",
    aboutUs: "معلومات عنا",
    benefitsPerks: "المزايا والفوائد",
    companySnapshot: "لمحة عن الشركة",
    founded: "تأسست في",
    field: "المجال",
    companySize: "حجم الشركة",
    headquarters: "المقر الرئيسي",
    visitWebsite: "زيارة الموقع",
    weAreHiring: "نحن نوظف!",
    joinOurTeam: "انضم إلى فريقنا وساعدنا في بناء المستقبل.",
    openRoles: "الأدوار المفتوحة",
    viewOpportunities: "عرض الفرص",
    corporatePartner: "شريك شركة",
    notAvailable: "غير متوفر",
    // InternshipDetails
    gatheringInfo: "جاري جمع معلومات التدريب...",
    couldNotFindInternship: "لم نتمكن من العثور على فرصة التدريب هذه.",
    goBack: "رجوع",
    positions: "مناصب",
    opportunityOverview: "نظرة عامة على الفرصة",
    requiredSkills: "المهارات المطلوبة",
    keyDetails: "تفاصيل رئيسية",
    startsOn: "يبدأ في",
    endsOn: "ينتهي في",
    timeLeft: "الوقت المتبقي",
    started: "بدأ",
    daysLeft: "أيام متبقية",
    dayLeft: "يوم متبقي",
    hoursLeft: "ساعات متبقية",
    duration: "المدة",
    flexible: "مرن",
    spotsFilled: "الأماكن الممتلئة",
    workMode: "وضع العمل",
    applicationRejected: "تم رفض الطلب",
    applicationAccepted: "تم قبول الطلب",
    applicationReceived: "تم استلام الطلب",
    cancelApplication: "إلغاء الطلب",
    wait: "انتظر...",
    cannotApplyAgain: "لا يمكنك التقديم مرة أخرى لهذا التدريب المحدد.",
    applyNow: "قدم الآن",
    cvRequired: "السيرة الذاتية مطلوبة",
    uploadCvUnlock: "يرجى تحميل سيرتك الذاتية في لوحة التحكم الخاصة بك لفتح الطلبات.",
    goToCvManager: "الذهاب إلى مدير السيرة الذاتية",
    sending: "جاري الإرسال...",
    // Forgot Password
    forgotPasswordTitle: "هل نسيت كلمة المرور؟",
    verifyCode: "تحقق من الرمز",
    newPasswordTitle: "كلمة مرور جديدة",
    forgotSubtitle1: "لا تقلق! أدخل بريدك الإلكتروني وسنرسل لك رمز إعادة التعيين.",
    forgotSubtitle2: "لقد أرسلنا رمزًا مكونًا من 6 أرقام إلى",
    forgotSubtitle3: "قم بإنشاء كلمة مرور جديدة قوية لحسابك.",
    enterEmailError: "يرجى إدخال عنوان بريدك الإلكتروني.",
    validEmailError: "يرجى إدخال بريد إلكتروني صحيح.",
    noAccountFound: "لا يوجد حساب بهذا البريد الإلكتروني.",
    somethingWentWrong: "حدث خطأ ما.",
    enter6Digit: "يرجى إدخال الرمز المكون من 6 أرقام.",
    invalidCode: "خطأ في الاتصال أو رمز غير صالح.",
    enterNewPassword: "يرجى إدخال كلمة مرور جديدة.",
    passwordLength: "يجب أن يكون 8 أحرف على الأقل.",
    confirmYourPassword: "يرجى تأكيد كلمة المرور.",
    passwordsDoNotMatch: "كلمات المرور غير متطابقة.",
    failedToReset: "فشل في إعادة تعيين كلمة المرور.",
    failedToResend: "فشل في إعادة الإرسال.",
    sendResetCode: "إرسال رمز إعادة التعيين",
    verifyCodeBtn: "التحقق من الرمز",
    didntReceive: "لم تستلم الرمز؟",
    resendIn: "إعادة الإرسال بعد",
    resendCode: "إعادة إرسال الرمز",
    newPasswordLabel: "كلمة المرور الجديدة",
    enterNewPasswordPlaceholder: "أدخل كلمة المرور الجديدة",
    confirmPasswordLabel: "تأكيد كلمة المرور",
    confirmPasswordPlaceholder: "تأكيد كلمة المرور الجديدة",
    weak: "ضعيف",
    fair: "متوسط",
    strong: "قوي",
    veryStrong: "قوي جداً",
    resetPasswordBtn: "إعادة تعيين كلمة المرور",
    passwordReset: "تمت إعادة تعيين كلمة المرور!",
    passwordResetSuccess: "تمت إعادة تعيين كلمة المرور بنجاح. يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.",
    backToSignIn: "العودة لتسجيل الدخول",
    // Sidebar
    sidebarDashboard: "لوحة التحكم",
    sidebarOverview: "نظرة عامة",
    sidebarAnalytics: "التحليلات",
    sidebarInternships: "التدريبات",
    sidebarBrowseAll: "تصفح الكل",
    sidebarMyListings: "إعلاناتي",
    sidebarNewPosting: "إعلان جديد",
    sidebarApplications: "الطلبات",
    sidebarPlatform: "المنصة",
    sidebarSettings: "الإعدادات",
    sidebarHelpCenter: "مركز المساعدة",
    sidebarMyCV: "سيرتي الذاتية",
    sidebarMyApplications: "طلباتي",
    sidebarUserManagement: "إدارة المستخدمين",
    sidebarCompanies: "الشركات",
    sidebarValidations: "التحققات",
    sidebarMessages: "الرسائل",
    searchPlaceholder: "بحث...",
    comingSoon: "قريباً...",
    studentPlatform: "منصة الطالب",
    companyPlatform: "منصة الشركة",
    platformAdmin: "مدير المنصة",
  },
};

const langCodeMap = {
  English: "en",
  Français: "fr",
  العربية: "ar",
};

const langNameMap = {
  en: "English",
  fr: "Français",
  ar: "العربية",
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem("app-language") || "en";
  });

  const changeLanguage = (lang) => {
    const code = langCodeMap[lang] || lang;
    setLanguage(code);
    localStorage.setItem("app-language", code);
  };

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, langNameMap, langCodeMap }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
